# This is public config file, do NOT put any secrets here
defaults: &defaults
  krakow:
    max_bounds:
      west: 19.79223802299622
      south: 49.96766514062150
      east: 20.20907913224060
      north: 50.12550879764089
  charts:
    interval: 15 # hours
  measurements:
    interval: 15 # minutes
  demo: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
